---
title: "Scheduled Emails"
output: html_notebook
---
```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
```

```{r library all the files}
library(RPostgreSQL)
library(dplyr)
library(dbplyr)
library(data.table)
library(lubridate)
library(reshape2)
library(stringr)
library("readxl")
library(writexl)
library(openxlsx)
library(tidyverse)
```

```{r inventory report - daily - send email (Internal)}
invetory_report <- paste("C:/Users/lisal/OneDrive - bookxchange.com/Retail Reporting/Reports/Inventory Report/Retail Internal/Inventory_Reports_Internal_", sep = "", today(), ".xlsx")
# install.packages('RDCOMClient', repos = 'http://www.omegahat.net/R/')
library(RDCOMClient)
## init com api
OutApp <- COMCreate("Outlook.Application")
## create an email 
outMail = OutApp$CreateItem(0)
## configure  email parameter 
outMail[["To"]] =  paste("lisal@bookxchange.com"
                         ,"pankajn@bookxchange.com"
                         ,"frankm@bookxchange.com",sep=";", collapse=NULL)
outMail[["subject"]] = paste0("Report | Inventory Reports - Textbooks & Trade Books", sep=" ", today())
outMail[["attachments"]]$Add(invetory_report)
outMail[["body"]] = 
"Hi Team, 
                      
Please see the attached inventory report (Raw Data)
                     
Let me know
             
Thank you

Caiwen(Lisa) Li | Data Scientist - BookXchange

35 SW 12 AVE | Dania Beach | FL 33004
lisal@bookxchange.com
"
## send it                     
outMail$Send()

```

```{r inventory report - daily - send email (Team)}
invetory_report <- "C:/Users/lisal/OneDrive - bookxchange.com/Retail Reporting/Reports/Inventory Report/BookXchange Team/Inventory Report/Inventory_Reports_DBConnection - V3.xlsx"
# install.packages('RDCOMClient', repos = 'http://www.omegahat.net/R/')
library(RDCOMClient)
## init com api
OutApp <- COMCreate("Outlook.Application")
## create an email 
outMail = OutApp$CreateItem(0)
## configure  email parameter 
outMail[["To"]] =  paste("lisal@bookxchange.com"
                         ,"Isaac@bookxchange.com"
                         ,"pankajn@bookxchange.com"
                         ,"davidk@bookxchange.com"
                         ,"ericab@bookxchange.com"
                         ,"frankm@bookxchange.com"
                         ,"GusC@bookxchange.com"
                         ,"vanessac@bookxchange.com"
                         ,"liviac@bookxchange.com"
                         ,"madelinem@bookxchange.com"
                         ,"mayarat@bookxchange.com"
                         ,"nicholasc@bookxchange.com",sep=";", collapse=NULL)
outMail[["subject"]] = paste0("Report | Inventory Reports ", sep=" ", today())
outMail[["attachments"]]$Add(invetory_report)
outMail[["body"]] = 
"Hi Team, 
                      
Please see the updated inventory report - WSpec added - (Due date report is also included)
                     
Let me know if you have any questions 

Thank you

Caiwen(Lisa) Li | Data Scientist - BookXchange

35 SW 12 AVE | Dania Beach | FL 33004
lisal@bookxchange.com
"
## send it                     
outMail$Send()

```

```{r wholesale price update report - weekly - Wed - send email (Team)}
wp_report <- "C:/Users/lisal/OneDrive - bookxchange.com/Retail Reporting/Reports/Wholesale Report/Wholesale Price/Wholesale_Pricing_Report_2020-12-23.xlsx"
## wp_query <- "C:/Users/lisal/Documents/SQL Server Management Studio/Wholesale Price Inventory Updated 2020-11-11.sql" - change needed

# install.packages('RDCOMClient', repos = 'http://www.omegahat.net/R/')
library(RDCOMClient)
## init com api
OutApp <- COMCreate("Outlook.Application")
## create an email 
outMail = OutApp$CreateItem9i
## configure  email parameter 
outMail[["To"]] =  paste("lisal@bookxchange.com"
                         ,"Isaac@bookxchange.com"
                         ,"frankm@bookxchange.com"
                         ,"madelinem@bookxchange.com"
                         ,"mayaram@bookxchange.com"
                         ,"mayarat@bookxchange.com"
                         ,"pankajn@bookxchange.com"
                         ,"davidk@bookxchange.com",sep=";", collapse=NULL)
outMail[["subject"]] = paste0("Price Updates | Wholesale Price & FBA Price Report", sep=" ", today())
outMail[["attachments"]]$Add(wp_report)
## outMail[["attachments"]]$Add(wp_query)
outMail[["body"]] = 
"Hi Team, 
                      
Please see the attached updated price and query (Textbooks + Trade books + Trouble books)

SQL Data is also updated for bid and use the query to get the live inventory + price

Please do not use the query for geting the inventory and price for now since we are experencing some technical issue with the connection. Will keep you updated once it is fixed
                     
Let me know if you have any questions/comments
             
Thank you

Caiwen(Lisa) Li | Data Scientist - BookXchange

35 SW 12 AVE | Dania Beach | FL 33004
lisal@bookxchange.com
"
## send it                     
outMail$Send()

```

```{r sale report - weekly - send email}
sale_report <- "C:/Users/lisal/OneDrive - bookxchange.com/Retail Reporting/Reports/Sale Report/Amz_Sales_Report_DBConnection.xlsx"
# install.packages('RDCOMClient', repos = 'http://www.omegahat.net/R/')
library(RDCOMClient)
## init com api
OutApp <- COMCreate("Outlook.Application")
## create an email 
outMail = OutApp$CreateItem(0)
## configure  email parameter 
outMail[["To"]] =  paste("lisal@bookxchange.com"
                         ,"pankajn@bookxchange.com"
                         ,"frankm@bookxchange.com"
                         ,"danielai@bookxchange.com"
                         ,"DZaret@bookxchange.com"
                         ,"ericab@bookxchange.com"
                         ,"mayarat@bookxchange.com"
                         ,"moshea@bookxchange.com"
                         ,"nicholasc@bookxchange.com"
                         ,"davidk@bookxchange.com",sep=";", collapse=NULL)
outMail[["subject"]] = paste0("Report | Weekly Sales Report - Amazon Total ", sep=" ", today())
outMail[["attachments"]]$Add(sale_report)
outMail[["body"]] = 
"Hi Team, 
                      
Please see the attached amazon sale report 
                     
Let me know if you have any questions/comments
             
Thank you

Caiwen(Lisa) Li | Data Scientist - BookXchange

35 SW 12 AVE | Dania Beach | FL 33004
lisal@bookxchange.com
"
## send it                     
outMail$Send()

```

```{r fifo report - twice per week - send email}
fifo_report <- "C:/Users/lisal/OneDrive - bookxchange.com/Retail Reporting/Reports/FIFO Report/FIFO_Report_V2.xlsx"
# install.packages('RDCOMClient', repos = 'http://www.omegahat.net/R/')
library(RDCOMClient)
## init com api
OutApp <- COMCreate("Outlook.Application")
## create an email 
outMail = OutApp$CreateItem(0)
## configure  email parameter 
outMail[["To"]] =  paste("lisal@bookxchange.com"
                         ,"frankm@bookxchange.com"
                         ,"pankajn@bookxchange.com"
                         ,"vanessac@bookxchange.com"
                         ,sep=";", collapse=NULL)
outMail[["subject"]] = paste0("Report | FIFO Cost - Textbooks & Trade books", sep=" ", today())
outMail[["attachments"]]$Add(fifo_report)
outMail[["body"]] = 
"Hi Frank, 
                      
Please see the updated FIFO Cost (all FIFO cost are included- No WSpec)

Please use this query to get FIFO SELECT * FROM [PROCUREMENTDB].[Retail].[FIFO] from database moving forward

Let me know if you have any questions/comments

Thank you

Caiwen(Lisa) Li | Data Scientist - BookXchange

35 SW 12 AVE | Dania Beach | FL 33004
lisal@bookxchange.com
"
## send it                     
outMail$Send()

```

```{r indaba inventory - twice per week - send email}
indaba_report <- paste("C:/Users/lisal/OneDrive - bookxchange.com/Retail Reporting/Reports/Indaba Inventory/Uploading Inventory/Full_inventory_", sep = "", today(), ".csv")
# install.packages('RDCOMClient', repos = 'http://www.omegahat.net/R/')
library(RDCOMClient)
## init com api
OutApp <- COMCreate("Outlook.Application")
## create an email 
outMail = OutApp$CreateItem(0)
## configure  email parameter 
outMail[["To"]] =  paste("lisal@bookxchange.com"
                         ,"pankajn@bookxchange.com"
                         ,"danielai@bookxchange.com",sep=";", collapse=NULL)
outMail[["subject"]] = paste0("Indaba Inventory | Textbooks ", sep=" ", today())
outMail[["attachments"]]$Add(indaba_report)
outMail[["body"]] = 
"Hi Daniela, 

Please see the indaba inventory file attached (AW + FBA) and upload it to the platform

Let me know if you have any questions
 
Thank you 
 
Caiwen(Lisa) Li
Data Scientist | BookXchange
35 SW 12 AVE | Dania Beach | FL 33004
lisal@bookxchange.com
"
## send it                     
outMail$Send()

```

```{r due date report - weekly - send email}
duedate_report <- ("C:/Users/lisal/OneDrive - bookxchange.com/Retail Reporting/Reports/Due Date Report/Due_Date_Report_DBConnection.xlsx")
library(RDCOMClient)
## init com api
OutApp <- COMCreate("Outlook.Application")
## create an email 
outMail = OutApp$CreateItem(0)
## configure  email parameter 
outMail[["To"]] =  paste("lisal@bookxchange.com"
                         ,"pankajn@bookxchange.com"
                         ,"Isaac@bookxchange.com"
                         ,"DZaret@bookxchange.com"
                         ,"frankm@bookxchange.com"
                         ,"GusC@bookxchange.com"
                         ,"mayarat@bookxchange.com"
                         ,"danielai@bookxchange.com"
                         ,"davidk@bookxchange.com", sep=";", collapse=NULL)
outMail[["subject"]] = paste0("Report | Due Date Report - Textbooks & Trade Books", sep=" ", today())
outMail[["attachments"]]$Add(duedate_report)
outMail[["body"]] = 
"Hi Pankaj, 
                      
Please see the attached due date report. 

Let me know if you have any questions/comments.
             
Thank you

Caiwen(Lisa) Li | Data Scientist - BookXchange

35 SW 12 AVE | Dania Beach | FL 33004
lisal@bookxchange.com
"
## send it                     
outMail$Send()

```

```{r velocity report - weekly - send email}
velocity_report <- paste("C:/Users/lisal/OneDrive - bookxchange.com/Retail Reporting/Reports/Velocity Report/Reports/Velocity_Report_", sep = "", today(), ".xlsx")
library(RDCOMClient)
## init com api
OutApp <- COMCreate("Outlook.Application")
## create an email 
outMail = OutApp$CreateItem(0)
## configure  email parameter 
outMail[["To"]] =  paste("lisal@bookxchange.com"
                         ,"pankajn@bookxchange.com"
                         ,"frankm@bookxchange.com"
                         ,"danielai@bookxchange.com", sep=";", collapse=NULL)
outMail[["subject"]] = paste0("Report | Weekly Velocity Report - Textbooks & Trade Books", sep=" ", today())
outMail[["attachments"]]$Add(velocity_report)
outMail[["body"]] = 
"Hi Team, 
                      
Please see the attached velocity report

Please note trade books velocity is added for the week and use the slicer for selecting

Let me know if you have any questions/comments
             
Thank you

Caiwen(Lisa) Li | Data Scientist - BookXchange

35 SW 12 AVE | Dania Beach | FL 33004
lisal@bookxchange.com
"
## send it                     
outMail$Send()


```
