---
title: "Task Schedules"
output: html_notebook
---

```{r Task Schedule Management}
library(taskscheduleR)

taskscheduler_delete(taskname = "Schedule_Task_Daily")
runon <- format(Sys.time() + 60, "%H:%M")
taskscheduler_create(taskname = "Schedule_Task_Daily", rscript = "C:/Users/lisal/Desktop/R_Schedule_Reports/Scheduled_Report_Daily.R", 
 schedule = "ONCE", starttime = runon)

taskscheduler_delete(taskname = "Schedule_Task_Weekly")
runon <- format(Sys.time() + 120, "%H:%M")
taskscheduler_create(taskname = "Schedule_Task_Weekly", rscript = "C:/Users/lisal/Desktop/R_Schedule_Reports/Scheduled_Report_Weekly.R", schedule = "ONCE", starttime = runon)

taskscheduler_create(taskname = "Daily_Schedule_Task", rscript = "C:/Users/lisal/Desktop/R_Schedule_Reports/Scheduled_Report_Daily.R", 
 schedule = "DAILY", starttime = "08:50", startdate = format(Sys.Date() + 1, "%d/%m/%Y"))

Sys.Date()
```

```{r Ready to go Code}
## Run every day at the same time on 09:10, starting from tomorrow on
## Mark: change the format of startdate to your locale if needed (e.g. US: %m/%d/%Y)
taskscheduler_create(taskname = "Daily_Schedule_Task", rscript = "C:/Users/lisal/Desktop/R_Schedule_Reports/Scheduled_Report_Daily.R", 
 schedule = "DAILY", starttime = "09:10", startdate = format(Sys.Date() + 1, "%d/%m/%Y"))
 
## Run every week on Sunday at 09:10
taskscheduler_create(taskname = "myfancyscript_sun", rscript = myscript, 
  schedule = "WEEKLY", starttime = "09:10", days = 'SUN')

## Run every 5 minutes, starting from 10:40
taskscheduler_create(taskname = "myfancyscript_5min", rscript = myscript,
  schedule = "MINUTE", starttime = "10:40", modifier = 240)
  
## Run every minute, giving some command line arguments which can be used in the script itself
taskscheduler_create(taskname = "myfancyscript_withargs_a", rscript = myscript,
  schedule = "MINUTE", rscript_args = "productxyz 20160101")

taskscheduler_create(taskname = "myfancyscript_withargs_b", rscript = myscript,
  schedule = "MINUTE", rscript_args = c("productabc", "20150101"))
  
alltasks <- taskscheduler_ls()
subset(alltasks, TaskName %in% c("myfancyscript", "myfancyscriptdaily"))
# The field TaskName might have been different on Windows with non-english language locale

taskscheduler_delete(taskname = "Daily_Schedule_Task")
taskscheduler_delete(taskname = "myfancyscriptdaily")
taskscheduler_delete(taskname = "myfancyscript_sun")
taskscheduler_delete(taskname = "myfancyscript_5min")
taskscheduler_delete(taskname = "myfancyscript_withargs_a")
taskscheduler_delete(taskname = "myfancyscript_withargs_b")
```

